# Setting Up Default Dockerfile For Backend E2E Tests For CI
FROM python:3.8.13-buster
RUN apt-get update && \
    apt-get install -y --install-recommends build-essential findutils
# Set WORKDIR to this dir, then copy content
WORKDIR /
# Copy all content
COPY . .
# Install dependencies 
RUN pip install --no-cache-dir -r test-requirements.txt