"""
Base class for Storage Network operations
Defines the interface for both CRD and REST implementations
"""
from abc import ABC, abstractmethod


class Base(ABC):
    """Base class for Storage Network implementations"""

    @abstractmethod
    def enable_storage_network(self, vlan_id, cluster_network, ip_range,
                               share_rwx=False):
        """Enable the storage-network Harvester setting.

        Args:
            vlan_id: VLAN ID for the storage network
            cluster_network: Cluster network name
            ip_range: CIDR IP range for storage network
            share_rwx: If True, include 'share-storage-network': true in the
                       setting value so Harvester automatically configures
                       Longhorn's endpoint-network-for-rwx-volume setting.
        """
        pass

    @abstractmethod
    def disable_storage_network(self):
        """Disable the storage-network Harvester setting."""
        pass

    @abstractmethod
    def get_storage_network_status(self):
        """Get the current storage-network setting status.

        Returns:
            dict: The storage-network setting data
        """
        pass

    @abstractmethod
    def wait_for_storage_network_ready(self, timeout):
        """Wait for storage-network setting to be applied and completed.

        Args:
            timeout: Timeout in seconds
        """
        pass

    @abstractmethod
    def get_vlan_network_cidr(self, vlan_id, cluster_network):
        """Get the CIDR for a VLAN network by creating a temporary network.

        Creates a temp VLAN network, reads the route annotation to get CIDR,
        then deletes the temp network.

        Args:
            vlan_id: VLAN ID
            cluster_network: Cluster network name

        Returns:
            str: CIDR string (e.g. '192.168.1.0/24')
        """
        pass

    @abstractmethod
    def enable_longhorn_rwx_storage_network(self):
        """Set the Longhorn 'endpoint-network-for-rwx-volume' setting
        to the same NAD used by Longhorn's storage-network setting.

        The NAD reference is read dynamically from the Longhorn
        'storage-network' setting (e.g. harvester-system/storagenetwork-xxxxx)
        rather than hardcoded, since the name is generated by Harvester."""
        pass

    @abstractmethod
    def disable_longhorn_rwx_storage_network(self):
        """Clear the Longhorn 'endpoint-network-for-rwx-volume' setting."""
        pass
