---
JENKINS_ADMIN_USERNAME: admin
JENKINS_ADMIN_PASSWORD: jenkins
JENKINS_ADMIN_EMAIL: gyee@suse.com
JENKINS_DEV_USERNAME: harvester
JENKINS_DEV_PASSWORD: harvester
JENKINS_PUBLIC_ENDPOINT: http://localhost:8080
