#!/bin/bash
TESTS_FAILED=false

xvfb-run --server-args='-screen 0 1024x768x16 -ac' yarn run e2e

if [ $? -ne 0 ]; then
  echo "Cypress tests failed."
  TESTS_FAILED=true
fi

timestamp=$(date +%Y%m%d-%H%M%S)
commit_id=$(git rev-parse --short HEAD)

report_dir="cypress/results/${timestamp}-${commit_id}"

mkdir -p ${report_dir}

cp -rf cypress/results/mochawesome-report/assets/ ${report_dir}

./node_modules/.bin/mochawesome-merge 'cypress/results/*.json' > ${report_dir}/merge.json 
./node_modules/.bin/marge ${report_dir}/merge.json -o ${report_dir} -f index.html

minio_dir="cypress-test-report/cypress/results/"
minio_name="minio"

mc alias set ${minio_name} $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --insecure

mc cp --recursive ${report_dir} ${minio_name}/${minio_dir} --insecure

if [ $TESTS_FAILED = true ]; then
  echo "Tests failed, but test results were still uploaded to MinIO."
fi
