#!/bin/bash
MINIO_ENDPOINT=$MINIO_ENDPOINT
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY

mc alias set minio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --insecure

mc cp --recursive minio/cypress-test-report/cypress/results/mochawesome-report/ /usr/share/nginx/html --insecure

mv /usr/share/nginx/html/mochawesome.html /usr/share/nginx/html/index.html

nginx -g "daemon off;"
