name: PEP8 Check 

on:
  push:
    paths-ignore:
      - docs/**
      - .github/**
  pull_request:
    paths-ignore:
      - docs/**
      - .github/**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e pep8
        
