---

- name: pki | _setup_root_ca | Create root-ca.conf
  template:
    src: root-ca.conf.j2
    dest: "{{ root_ca_conf_file }}"

- include: _setup_ca.yml
  vars:
    ca_type: root
    ca_dir: "{{ root_ca_dir }}"

- name: pki | _setup_root_ca | Create self-signed root CA certificate
  command: |
    openssl req
      -new
      -config "{{ root_ca_conf_file }}"
      -out "{{ root_ca_cert_file }}"
      -key "{{ root_ca_key_file }}"
      -x509
      -days 3652
      -sha256
      -extensions v3_ca
  args:
    creates: "{{ root_ca_cert_file }}"

- name: pki | _setup_root_ca | Copy root CA certificate to {{ certs_dir }}
  copy:
    remote_src: true
    src: "{{ root_ca_cert_file }}"
    dest: "{{ certs_dir }}"
    owner: root
    group: root
    mode: 0744
